FROM rust:1.43


WORKDIR /root/damia
ENV USER=root
RUN rustup component add rust-src rust-analysis rls
# RUN rustup add rustfmt --toolchain 1.31.1-x86_64-unknown-linux-gnu

# COPY . .

# RUN cargo install --path .

# CMD ["myapp"]