FROM golang:1.16-buster

COPY .. /root/workspace
WORKDIR /root/workspace/src

RUN go get -v \
    github.com/inconshreveable/mousetrap \
    github.com/ramya-rao-a/go-outline \
    github.com/ramya-rao-a/go-outline \
    github.com/cweill/gotests/gotests \
    github.com/fatih/gomodifytags \
    github.com/josharian/impl \
    github.com/haya14busa/goplay/cmd/goplay \
    github.com/go-delve/delve/cmd/dlv \
    honnef.co/go/tools/cmd/staticcheck \
    golang.org/x/tools/gopls


RUN go build